name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 4321
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo "ğŸ”§ Fix permissions early..."
            sudo chown -R $USER:www-data .
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            echo "ğŸ” Git safe directory setup..."
            git config --global --add safe.directory $(pwd)

            echo "ğŸš§ Mise en maintenance..."
            php artisan down || true

            echo "ğŸ“¥ Pull du code..."
            git pull origin main

            echo "ğŸ“¦ Installation des dÃ©pendances..."
            composer install --no-dev --optimize-autoloader --ignore-platform-reqs

            echo "âš™ï¸  Clear & cache Laravel config..."
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear

            echo "ğŸ§± Migration & seed..."
            php artisan migrate --seed --force

            echo "âœ… Application online"
            php artisan up

            echo "ğŸ” API health check..."
            curl -k --fail https://qrscanapi.matthisripoche.com/api/health || exit 1
