name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 4321
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo "ğŸš§ Mise en maintenance..."
            php artisan down || true

            echo "ğŸ“¥ Pull du code..."
            git pull origin main

            echo "ğŸ“¦ Installation des dÃ©pendances..."
            composer install --no-dev --optimize-autoloader

            echo "ğŸ”§ Permissions des dossiers Laravel..."
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            echo "âš™ï¸  Cache & migrations..."
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:clear
            php artisan migrate:fresh --seed --force

            echo "âœ… Mise en production terminÃ©e."
            php artisan up

            echo "ğŸ” VÃ©rification de lâ€™Ã©tat de lâ€™API..."
            curl --fail https://qrscanapi.matthisripoche.com/api/health || exit 1
